# Week 1 NumPy Project: Real Estate Market Analysis

## Background

You are a Data Analyst working with a real estate company. Your task is to analyze property data using **NumPy** and identify patterns in property prices and characteristics.

## Dataset

Use the **Housing Prices Regression** dataset from Kaggle:

https://www.kaggle.com/datasets/denkuznetz/housing-prices-regression

## Tasks

### 1. Load and Explore the Data

**NumPy concepts: Structured Arrays, Indexing**

* Load the CSV dataset using NumPy.
* Load it as a structured array.
* Inspect the shape, fields, and data types.
* Display the first 5 records.

### 2. Analyze Property Prices

**NumPy concepts: Indexing, Aggregation Functions**

* Extract the property price data.
* Calculate the mean, median, minimum, maximum, and percentiles.
* Briefly interpret your findings.

### 3. Analyze Property Size

**NumPy concepts: Indexing, Aggregation Functions**

* Extract the property size data.
* Calculate the mean, median, minimum, and maximum.
* Briefly describe the distribution of property sizes.

### 4. Calculate Price per Square Foot

**NumPy concepts: Element-wise Array Operations**

* Calculate the price per square foot for each property.
* Calculate the mean, median, minimum, and maximum.
* Briefly interpret the results.

### 5. Identify Expensive Properties

**NumPy concepts: Boolean Masking, Aggregation Functions**

Identify properties whose prices fall within the **top 25%** of the dataset.

Determine:

* Number of properties
* Average price
* Comparison with the overall average price

### 6. Apply Multiple Conditions

**NumPy concepts: Boolean Masking, Multiple Boolean Conditions**

Identify properties that:

* Are larger than the average property size
* Are in the top 25% by price
* Have a location score of at least 8

Determine how many properties meet all three conditions and examine their characteristics.

### 7. Compare Prices to the Average

**NumPy concept: Broadcasting**

Compare every property's price with the overall average property price.

Identify properties that are above and below the average.

Briefly explain how broadcasting was applied.

### 8. Find the 10 Most Expensive Properties

**NumPy concepts: Sorting, Fancy Indexing**

* Sort the property prices.
* Identify the 10 most expensive properties.
* Use fancy indexing to retrieve their IDs, sizes, number of bedrooms, location scores, and prices.

### 9. Final Analysis

Compare the characteristics of the **10 most expensive properties** with the overall dataset.

Consider:

* Property size
* Number of bedrooms
* Location score

Answer:

> **What characteristics tend to be associated with the most expensive properties in this dataset?**

Write a short **3–5 sentence business insight** based on your analysis.

## Submission

Submit **one Jupyter Notebook (`.ipynb`)** containing your code, outputs, interpretations, and final business insight.


In [1]:
import numpy as np

In [2]:
data = np.genfromtxt(
    "real_estate_dataset.csv",
    delimiter=",",
    names=True,
    dtype=None,
    encoding="utf-8"
)

In [3]:
data.shape

(500,)

In [7]:
data[0]

np.void((1, 143.63502971184062, 1, 3, 3, 1967, 1, 1, 48, 8.297631202876449, 5.935733640397012, 602134.816746586), dtype=[('ID', '<i8'), ('Square_Feet', '<f8'), ('Num_Bedrooms', '<i8'), ('Num_Bathrooms', '<i8'), ('Num_Floors', '<i8'), ('Year_Built', '<i8'), ('Has_Garden', '<i8'), ('Has_Pool', '<i8'), ('Garage_Size', '<i8'), ('Location_Score', '<f8'), ('Distance_to_Center', '<f8'), ('Price', '<f8')])

In [4]:
data.dtype

dtype([('ID', '<i8'), ('Square_Feet', '<f8'), ('Num_Bedrooms', '<i8'), ('Num_Bathrooms', '<i8'), ('Num_Floors', '<i8'), ('Year_Built', '<i8'), ('Has_Garden', '<i8'), ('Has_Pool', '<i8'), ('Garage_Size', '<i8'), ('Location_Score', '<f8'), ('Distance_to_Center', '<f8'), ('Price', '<f8')])

In [5]:
data[:5]

array([(1, 143.63502971, 1, 3, 3, 1967, 1, 1, 48, 8.2976312 ,  5.93573364, 602134.81674659),
       (2, 287.6785766 , 1, 2, 1, 1949, 0, 1, 37, 6.06146565, 10.8273922 , 591425.13538622),
       (3, 232.99848545, 1, 3, 2, 1923, 1, 0, 14, 2.91144248,  6.90459907, 464478.69687988),
       (4, 199.66462105, 5, 2, 2, 1918, 0, 0, 17, 2.07094918,  8.28401851, 583105.65599648),
       (5,  89.00466011, 4, 3, 3, 1999, 1, 0, 34, 1.52327786, 14.6482773 , 619879.14252279)],
      dtype=[('ID', '<i8'), ('Square_Feet', '<f8'), ('Num_Bedrooms', '<i8'), ('Num_Bathrooms', '<i8'), ('Num_Floors', '<i8'), ('Year_Built', '<i8'), ('Has_Garden', '<i8'), ('Has_Pool', '<i8'), ('Garage_Size', '<i8'), ('Location_Score', '<f8'), ('Distance_to_Center', '<f8'), ('Price', '<f8')])

In [6]:
data["Price"]

array([602134.81674659, 591425.13538622, 464478.69687988, 583105.65599648,
       619879.14252279, 670386.80443309, 523827.12560061, 875352.54518835,
       738269.85234248, 490552.68124045, 488942.1312444 , 677623.46678196,
       685123.5340515 , 658652.7892523 , 413729.07432785, 523527.97467754,
       527769.81302754, 514260.99504371, 581392.93584324, 750687.61985624,
       832883.87281184, 479876.36463862, 437751.64301541, 629162.35601462,
       394665.75095621, 651471.40649281, 563531.47692812, 528557.48604873,
       466357.44182484, 428376.72080725, 438805.86960758, 408507.95279093,
       592796.96272544, 506721.273236  , 595676.97931145, 504981.60357427,
       584118.04680365, 493819.27248399, 749855.05936678, 690863.19889222,
       352899.27426396, 524483.18424355, 531302.35515804, 610874.18218479,
       499521.04630341, 848335.00502405, 532329.5565179 , 649521.65100559,
       519049.39294636, 542062.85256993, 622563.36097648, 570832.17046021,
       909199.56036649, 6

In [8]:
print(data["Price"][:10])
print(data["Square_Feet"][:10])
print(data["Num_Bedrooms"][:10])
print(data["Price"].dtype)
print(data["Num_Bedrooms"].dtype)

[602134.81674659 591425.13538622 464478.69687988 583105.65599648
 619879.14252279 670386.80443309 523827.12560061 875352.54518835
 738269.85234248 490552.68124045]
[143.63502971 287.6785766  232.99848545 199.66462105  89.00466011
  88.99863008  64.52090304 266.54403644 200.27875294 227.01814445]
[1 1 1 5 4 5 4 5 5 3]
float64
int64


In [9]:
price = data["Price"]

print("Mean:", np.mean(price))
print("Median:", np.median(price))
print("Minimum:", np.min(price))
print("Maximum:", np.max(price))

Mean: 582209.6295285609
Median: 574724.1133467213
Minimum: 276892.4701358937
Maximum: 960678.274291193


In [10]:
price_range = np.max(price) - np.min(price)

print("Price range:", price_range)

Price range: 683785.8041552993


In [11]:
print("25th percentile:", np.percentile(price, 25))
print("50th percentile:", np.percentile(price, 50))
print("75th percentile:", np.percentile(price, 75))

25th percentile: 503080.3441399783
50th percentile: 574724.1133467213
75th percentile: 665942.3012741683


In [12]:
square_feet = data["Square_Feet"]

In [13]:
print("Mean:", np.mean(square_feet))
print("Median:", np.median(square_feet))
print("Minimum:", np.min(square_feet))
print("Maximum:", np.max(square_feet))

Mean: 174.6404280585035
Median: 178.2909370891116
Minimum: 51.265395961554674
Maximum: 298.2411990298251


In [14]:
price_per_sqft = price / square_feet

In [15]:
print(price_per_sqft[:10])

[4192.11676953 2055.85394078 1993.48376011 2920.42552623 6964.56951526
 7532.55194827 8118.71968468 3284.08227349 3686.21155025 2160.85230734]


In [16]:
print("Mean:", np.mean(price_per_sqft))
print("Median:", np.median(price_per_sqft))
print("Minimum:", np.min(price_per_sqft))
print("Maximum:", np.max(price_per_sqft))

Mean: 4008.8199858500298
Median: 3361.191343306035
Minimum: 1636.479625987531
Maximum: 11572.993341369523


In [17]:
expensive_mask = price > np.percentile(price, 75)

In [18]:
print(expensive_mask[:10])

[False False False False False  True False  True  True False]


In [19]:
expensive_prices = price[expensive_mask]

print(expensive_prices)

[670386.80443309 875352.54518835 738269.85234248 677623.46678196
 685123.5340515  750687.61985624 832883.87281184 749855.05936678
 690863.19889222 848335.00502405 909199.56036649 695024.31070497
 685065.87151435 854304.12719063 667693.00027559 814846.453707
 679084.03335289 788180.23305109 715176.7624918  802007.17254936
 730197.48060697 860013.25820393 787131.56969077 670086.00892323
 742958.51213822 674092.46628744 743412.14388911 687695.42703741
 819696.52555103 714280.62794187 682189.63058302 960678.27429119
 696835.45535427 688446.03851573 821184.1909183  783157.15952517
 773901.53313205 731778.40487664 671524.99983952 776835.04434834
 767053.86296846 693249.73514015 666645.84819004 762589.62917138
 885909.21527569 700016.11503443 710519.23687597 685888.33945309
 735994.91439405 717337.67458832 686120.90316574 702159.56982471
 824524.73308191 747371.30601713 739222.53853327 827018.65537275
 698491.78550813 705130.39803851 792066.34701914 713007.18350084
 692424.79205162 789119.858

In [20]:
print("Number of expensive properties:", np.sum(expensive_mask))

Number of expensive properties: 125


In [21]:
print("Average price of expensive properties:",
      np.mean(expensive_prices))

Average price of expensive properties: 744142.5268736309


In [22]:
print("Overall average price:",
      np.mean(price))

Overall average price: 582209.6295285609


In [23]:
large_mask = square_feet > np.mean(square_feet)

In [24]:
location_score = data["Location_Score"]

well_located_mask = location_score >= 8

In [25]:
large_expensive_well_located = (
    large_mask &
    expensive_mask &
    well_located_mask
)

In [26]:
print(np.sum(large_expensive_well_located))

17


In [27]:
selected = data[large_expensive_well_located]

print(selected)

[(  8, 266.54403644, 5, 1, 3, 1973, 1, 1, 39, 9.37378438, 12.69278513, 875352.54518835)
 ( 63, 257.18437729, 4, 1, 3, 1941, 0, 0, 33, 9.94981369,  8.09137313, 695024.31070497)
 (113, 282.42441309, 3, 3, 2, 2015, 0, 0, 13, 9.01383097, 13.24967894, 787131.56969077)
 (127, 254.50369148, 3, 3, 1, 2005, 0, 0, 46, 9.92442289,  7.72423986, 743412.14388911)
 (151, 277.06647149, 5, 2, 3, 2019, 1, 1, 30, 9.03757572, 13.09418151, 960678.27429119)
 (201, 210.50791154, 5, 3, 2, 2000, 1, 1, 42, 8.18026749, 18.33206603, 885909.21527569)
 (273, 266.76807965, 5, 2, 1, 1977, 1, 0, 13, 9.52467117,  4.92572038, 789119.85805756)
 (314, 290.66210367, 4, 2, 1, 1996, 0, 0, 28, 9.90361782,  4.39413581, 789822.93141469)
 (323, 215.04934418, 5, 1, 3, 1992, 0, 0, 19, 9.78957507, 15.53606664, 747398.27978378)
 (383, 207.23571169, 5, 3, 3, 1967, 0, 1, 36, 8.07189319,  3.30604572, 845911.3698025 )
 (384, 269.36800338, 5, 1, 1, 1933, 1, 0, 34, 8.61319626, 17.08521578, 676685.28252529)
 (397, 264.60318796, 5, 3, 2, 19

In [28]:
print("IDs:", selected["ID"])
print("Size:", selected["Square_Feet"])
print("Location Score:", selected["Location_Score"])
print("Price:", selected["Price"])

IDs: [  8  63 113 127 151 201 273 314 323 383 384 397 426 463 470 481 485]
Size: [266.54403644 257.18437729 282.42441309 254.50369148 277.06647149
 210.50791154 266.76807965 290.66210367 215.04934418 207.23571169
 269.36800338 264.60318796 187.38222058 236.51121982 290.80563486
 207.34965953 196.07857798]
Location Score: [9.37378438 9.94981369 9.01383097 9.92442289 9.03757572 8.18026749
 9.52467117 9.90361782 9.78957507 8.07189319 8.61319626 9.11521293
 9.15257185 9.24561055 8.28116829 8.28871276 8.84376547]
Price: [875352.54518835 695024.31070497 787131.56969077 743412.14388911
 960678.27429119 885909.21527569 789119.85805756 789822.93141469
 747398.27978378 845911.3698025  676685.28252529 842272.5390884
 669863.66424921 702645.57191937 708362.28705089 695642.10654902
 723834.85205224]


In [29]:
average_price = np.mean(price)

price_difference = price - average_price

print(price_difference[:10])

[  19925.18721803    9215.50585766 -117730.93264868     896.02646792
   37669.51299423   88177.17490452  -58382.50392795  293142.91565979
  156060.22281392  -91656.94828811]


In [30]:
print(price_difference[:10])

[  19925.18721803    9215.50585766 -117730.93264868     896.02646792
   37669.51299423   88177.17490452  -58382.50392795  293142.91565979
  156060.22281392  -91656.94828811]


In [31]:
sorted_indices = np.argsort(price)

top_10_indices = sorted_indices[-10:]

top_10_prices = price[top_10_indices]

print(top_10_prices)

[854304.12719063 854374.5244548  857487.18174448 860013.25820393
 864299.5002175  867558.29676918 875352.54518835 885909.21527569
 909199.56036649 960678.27429119]


In [32]:
top_10_indices = sorted_indices[-10:]

In [33]:
price[top_10_indices]

array([854304.12719063, 854374.5244548 , 857487.18174448, 860013.25820393,
       864299.5002175 , 867558.29676918, 875352.54518835, 885909.21527569,
       909199.56036649, 960678.27429119])

In [34]:
top_10_ids = data["ID"][top_10_indices]
top_10_sizes = data["Square_Feet"][top_10_indices]
top_10_bedrooms = data["Num_Bedrooms"][top_10_indices]
top_10_locations = data["Location_Score"][top_10_indices]

print("IDs:", top_10_ids)
print("Size:", top_10_sizes)
print("Bedrooms:", top_10_bedrooms)
print("Location Scores:", top_10_locations)
print("Prices:", price[top_10_indices])

IDs: [ 70 379 368 108 500 474   8 201  53 151]
Size: [296.72173415 253.61712065 276.33766049 238.88778464 296.55268612
 272.78577842 266.54403644 210.50791154 284.87473539 277.06647149]
Bedrooms: [4 5 4 5 4 5 5 5 5 5]
Location Scores: [4.0667407  7.42824975 3.85613513 2.53821078 7.89432194 6.32216598
 9.37378438 8.18026749 7.60854345 9.03757572]
Prices: [854304.12719063 854374.5244548  857487.18174448 860013.25820393
 864299.5002175  867558.29676918 875352.54518835 885909.21527569
 909199.56036649 960678.27429119]


In [35]:
print("Top 10 average size:", np.mean(top_10_sizes))
print("Overall average size:", np.mean(square_feet))

print("Top 10 average bedrooms:", np.mean(top_10_bedrooms))
print("Overall average bedrooms:", np.mean(data["Num_Bedrooms"]))

print("Top 10 average location score:", np.mean(top_10_locations))
print("Overall average location score:", np.mean(data["Location_Score"]))

Top 10 average size: 267.3895919331576
Overall average size: 174.6404280585035
Top 10 average bedrooms: 4.7
Overall average bedrooms: 2.958
Top 10 average location score: 6.630599531469035
Overall average location score: 5.1644099835214
